events {}

http {
    server {
        listen 80;

        location /health {
            access_log off;
            return 200 "OK\n";
            add_header Content-Type text/plain;
        }

        location / {
            return 200 "sentinel-nginx is running\n";
            add_header Content-Type text/plain;
        }
    }
}
